$(document).ready(function(){
    $("#what1").click(function(){
      $("#p1").toggle();
      $("#img1").toggle();
    });
    $("#what2").click(function(){
        $("#p2").toggle();
        $("#img2").toggle();
      });
      $("#what3").click(function(){
        $("#p3").toggle();
        $("#img3").toggle();
      });
  });